services:
  workspace:
    image: mcr.microsoft.com/devcontainers/python:3.12
    command: sleep infinity
    volumes:
      - ..:/workspace:cached
      - metaflow_data:/workspace/metaflow_data
      - mlruns:/workspace/mlruns
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - METAFLOW_DATASTORE_SYSROOT_S3=s3://metaflow
      - AWS_ACCESS_KEY_ID=minio
      - AWS_SECRET_ACCESS_KEY=minio123
      - AWS_DEFAULT_REGION=us-east-1
    depends_on:
      - minio
      - mlflow
      - labelstudio
    ports:
      - 8888:8888

  minio:
    image: minio/minio
    command: server /data/minio --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio_data:/data/minio

  mlflow:
    image: python:3.12
    command: >
      sh -c "pip install mlflow && mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri sqlite:///mlflow.db --default-artifact-root /workspace/mlruns"
    ports:
      - 5000:5000
    volumes:
      - mlruns:/workspace/mlruns

  labelstudio:
    image: heartexlabs/label-studio:latest
    ports:
      - 8080:8080
    environment:
      - LABEL_STUDIO_USERNAME=admin
      - LABEL_STUDIO_PASSWORD=admin

volumes:
  minio_data:
  mlruns:
  metaflow_data:
